apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  labels:
    app: solana-monitoring-service-mainnet
  name: solana-monitoring-service-mainnet
  namespace: default
  resourceVersion: "65918483"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: solana-monitoring-service-mainnet
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solana-monitoring-service-mainnet
    spec:
      containers:
        - env:
            - name: ENVIROMENT
              value: 'production'
            - name: NETWORK_NAME
              value: "mainnet-beta"
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  key: MAINNET_RPC_URL
                  name: env-vars
            - name: DIALECT_SDK_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: SOLANA_MESSAGING_PRIVATE_KEY_MAINNET
                  name: env-vars
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  key: TWILIO_ACCOUNT_SID
                  name: env-vars
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWILIO_AUTH_TOKEN
                  name: env-vars
            - name: TWILIO_SMS_SENDER
              value: "+15613366687"
            - name: WEB2_SUBSCRIBER_SERVICE_BASE_URL
              value: "https://dialectapi.to"
            - name: WEB2_SUBSCRIBER_SERVICE_BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  key: WALLET_ADDRESS_REGISTRY_SERVICE_BASIC_AUTH_USER
                  name: env-vars
            - name: SENDGRID_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: env-vars
            - name: SENDGRID_EMAIL
              value: "hello@dialect.to"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_TOKEN
                  name: env-vars
          image: dialectlab/solana-monitoring-service:0.1.0
          imagePullPolicy: Always
          name: solana-monitoring-service-mainnet
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
